### ISSUE TITLE
Feature request: Faster skipping of already obtained videos

### ISSUE THREAD

**Issue by hungLink** [NobilityDeviant/ZenDownloader#9]
Due to [issues I'm facing trying to download one piece english subbed](https://github.com/NobilityDeviant/ZenDownloader/issues/8), I would like it if the program would more quickly identify that it has downloaded an episode already.

This seems like it should be possible by looking at download history, or existing files; however it seems like the way it is doing it now requires it to look on wcofun for the filename, and then compare that to something locally. I think this may take longer than necessary, but I don't know how to fix it.

**Comment by NobilityDeviant** [comment]
This has always been something i've wanted to do but never tried after I actually started forcing the database to be downloaded. I can definitely do local comparisons of the file size now.

**Comment by hungLink** [comment]
That's sick. Thank you for being so responsive! I appreciate your efforts!

**Comment by NobilityDeviant** [comment]
Ok now I remember why it's so hard to do this.

The reason why it actually checks the video before this is because it needs to get the quality links & the file sizes for each first.

I can't save the links because they get auto generated every time.

I did have an idea to save the file size in the actual episode which will require an entire new database, but i think the improvements in:

[Commit](https://github.com/NobilityDeviant/ZenDownloader/commit/03e4c28864aeeb9e00fb39cfbce8e1c4ca69d2f1)

Will help without it.

This will be marked as low priority (at least in my brain) for now but I will do this in the next week or so.

**Comment by NobilityDeviant** [comment]
Ok I did actually add something last minute for cached downloads.

Let me know if the changes helped at all in the latest [release](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.4)

**Comment by NobilityDeviant** [comment]
Ok i'm going to close this. I attempted to restructure the database to include file sizes, but it's unreliable and resource heavy. 
I'll keep this in my back pocket, but overall it's not worth it unless this repo had way more traffic or more hands willing to help.
